#!/usr/bin/env bash
# PreToolUse hook: deny edits to generated / vendored files.
# Reads the hook input JSON on stdin, exits 2 (blocking) if file_path is forbidden.
set -euo pipefail

input="$(cat)"
file_path="$(printf '%s' "$input" | jq -r '.tool_input.file_path // empty')"

# Nothing to check — let the tool proceed.
[ -z "$file_path" ] && exit 0

case "$file_path" in
  */bun.lock|bun.lock)
    echo "blocked: bun.lock is generated by 'bun install' — do not hand-edit. Run 'bun install <pkg>' instead." >&2
    exit 2
    ;;
  */node_modules/*|node_modules/*)
    echo "blocked: node_modules/ is vendored — changes will be lost on next install. Edit the source package or vendor a patch with 'patch-package'." >&2
    exit 2
    ;;
esac

exit 0
